"""initial

Revision ID: b63cf960164a
Revises: 
Create Date: 2025-10-25 13:28:22.309243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63cf960164a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("status IN ('active', 'processing', 'completed', 'error')", name='observation_groups_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('length(login) >= 6 AND length(login) <= 20', name='user_table_login_check'),
    sa.CheckConstraint('octet_length(password_hash::bytea) = 40', name='user_table_password_hash_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login', name='user_login_unique')
    )
    op.create_table('observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('observation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('right_ascension', sa.String(length=50), nullable=False),
    sa.Column('declination', sa.String(length=50), nullable=False),
    sa.Column('observer_name', sa.String(length=100), nullable=True),
    sa.Column('observation_notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('declination::double precision >= -90 AND declination::double precision <= 90', name='valid_dec'),
    sa.CheckConstraint('right_ascension::double precision >= 0 AND right_ascension::double precision < 360', name='valid_ra'),
    sa.ForeignKeyConstraint(['group_id'], ['observation_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orbital_parameters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('semi_major_axis', sa.String(length=50), nullable=False),
    sa.Column('eccentricity', sa.String(length=50), nullable=False),
    sa.Column('inclination', sa.String(length=50), nullable=False),
    sa.Column('longitude_ascending_node', sa.String(length=50), nullable=False),
    sa.Column('argument_perihelion', sa.String(length=50), nullable=False),
    sa.Column('time_perihelion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculation_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('used_observations_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('eccentricity::double precision >= 0', name='valid_eccentricity'),
    sa.CheckConstraint('inclination::double precision >= 0 AND inclination::double precision <= 180', name='valid_inclination'),
    sa.CheckConstraint('longitude_ascending_node::double precision >= 0 AND longitude_ascending_node::double precision < 360 AND argument_perihelion::double precision >= 0 AND argument_perihelion::double precision < 360', name='valid_angles'),
    sa.CheckConstraint('semi_major_axis::double precision > 0', name='positive_semi_major_axis'),
    sa.ForeignKeyConstraint(['group_id'], ['observation_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close_approaches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('orbital_parameters_id', sa.UUID(), nullable=False),
    sa.Column('approach_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('distance_au', sa.String(length=50), nullable=False),
    sa.Column('distance_km', sa.String(length=50), nullable=False),
    sa.Column('calculation_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('distance_au::double precision > 0 AND distance_km::double precision > 0', name='positive_distance'),
    sa.ForeignKeyConstraint(['group_id'], ['observation_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orbital_parameters_id'], ['orbital_parameters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('close_approaches')
    op.drop_table('orbital_parameters')
    op.drop_table('observations')
    op.drop_table('user_table')
    op.drop_table('observation_groups')
    # ### end Alembic commands ###